version: "3"

services:
  todo-data:
    image: mongo:latest
    networks:
      - todo-app
    volumes:
      - mongo-data:/data/db

  todo-back:
    image: todo-back
    ports:
      - "8080:8080"
    networks:
      - todo-app

networks:
  todo-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
