// Code generated by counterfeiter. DO NOT EDIT.
package dbfakes

import (
	"sync"
	"todo-back/config"
	database "todo-back/db"
	"todo-back/model"
)

type FakeDatabaseManagerInterface struct {
	CloseDatabaseStub        func()
	closeDatabaseMutex       sync.RWMutex
	closeDatabaseArgsForCall []struct {
	}
	EstablishDatabaseConnectionStub        func(config.Config) error
	establishDatabaseConnectionMutex       sync.RWMutex
	establishDatabaseConnectionArgsForCall []struct {
		arg1 config.Config
	}
	establishDatabaseConnectionReturns struct {
		result1 error
	}
	establishDatabaseConnectionReturnsOnCall map[int]struct {
		result1 error
	}
	GetAllTodosStub        func() ([]model.Todo, error)
	getAllTodosMutex       sync.RWMutex
	getAllTodosArgsForCall []struct {
	}
	getAllTodosReturns struct {
		result1 []model.Todo
		result2 error
	}
	getAllTodosReturnsOnCall map[int]struct {
		result1 []model.Todo
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDatabaseManagerInterface) CloseDatabase() {
	fake.closeDatabaseMutex.Lock()
	fake.closeDatabaseArgsForCall = append(fake.closeDatabaseArgsForCall, struct {
	}{})
	stub := fake.CloseDatabaseStub
	fake.recordInvocation("CloseDatabase", []interface{}{})
	fake.closeDatabaseMutex.Unlock()
	if stub != nil {
		fake.CloseDatabaseStub()
	}
}

func (fake *FakeDatabaseManagerInterface) CloseDatabaseCallCount() int {
	fake.closeDatabaseMutex.RLock()
	defer fake.closeDatabaseMutex.RUnlock()
	return len(fake.closeDatabaseArgsForCall)
}

func (fake *FakeDatabaseManagerInterface) CloseDatabaseCalls(stub func()) {
	fake.closeDatabaseMutex.Lock()
	defer fake.closeDatabaseMutex.Unlock()
	fake.CloseDatabaseStub = stub
}

func (fake *FakeDatabaseManagerInterface) EstablishDatabaseConnection(arg1 config.Config) error {
	fake.establishDatabaseConnectionMutex.Lock()
	ret, specificReturn := fake.establishDatabaseConnectionReturnsOnCall[len(fake.establishDatabaseConnectionArgsForCall)]
	fake.establishDatabaseConnectionArgsForCall = append(fake.establishDatabaseConnectionArgsForCall, struct {
		arg1 config.Config
	}{arg1})
	stub := fake.EstablishDatabaseConnectionStub
	fakeReturns := fake.establishDatabaseConnectionReturns
	fake.recordInvocation("EstablishDatabaseConnection", []interface{}{arg1})
	fake.establishDatabaseConnectionMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDatabaseManagerInterface) EstablishDatabaseConnectionCallCount() int {
	fake.establishDatabaseConnectionMutex.RLock()
	defer fake.establishDatabaseConnectionMutex.RUnlock()
	return len(fake.establishDatabaseConnectionArgsForCall)
}

func (fake *FakeDatabaseManagerInterface) EstablishDatabaseConnectionCalls(stub func(config.Config) error) {
	fake.establishDatabaseConnectionMutex.Lock()
	defer fake.establishDatabaseConnectionMutex.Unlock()
	fake.EstablishDatabaseConnectionStub = stub
}

func (fake *FakeDatabaseManagerInterface) EstablishDatabaseConnectionArgsForCall(i int) config.Config {
	fake.establishDatabaseConnectionMutex.RLock()
	defer fake.establishDatabaseConnectionMutex.RUnlock()
	argsForCall := fake.establishDatabaseConnectionArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDatabaseManagerInterface) EstablishDatabaseConnectionReturns(result1 error) {
	fake.establishDatabaseConnectionMutex.Lock()
	defer fake.establishDatabaseConnectionMutex.Unlock()
	fake.EstablishDatabaseConnectionStub = nil
	fake.establishDatabaseConnectionReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDatabaseManagerInterface) EstablishDatabaseConnectionReturnsOnCall(i int, result1 error) {
	fake.establishDatabaseConnectionMutex.Lock()
	defer fake.establishDatabaseConnectionMutex.Unlock()
	fake.EstablishDatabaseConnectionStub = nil
	if fake.establishDatabaseConnectionReturnsOnCall == nil {
		fake.establishDatabaseConnectionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.establishDatabaseConnectionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDatabaseManagerInterface) GetAllTodos() ([]model.Todo, error) {
	fake.getAllTodosMutex.Lock()
	ret, specificReturn := fake.getAllTodosReturnsOnCall[len(fake.getAllTodosArgsForCall)]
	fake.getAllTodosArgsForCall = append(fake.getAllTodosArgsForCall, struct {
	}{})
	stub := fake.GetAllTodosStub
	fakeReturns := fake.getAllTodosReturns
	fake.recordInvocation("GetAllTodos", []interface{}{})
	fake.getAllTodosMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDatabaseManagerInterface) GetAllTodosCallCount() int {
	fake.getAllTodosMutex.RLock()
	defer fake.getAllTodosMutex.RUnlock()
	return len(fake.getAllTodosArgsForCall)
}

func (fake *FakeDatabaseManagerInterface) GetAllTodosCalls(stub func() ([]model.Todo, error)) {
	fake.getAllTodosMutex.Lock()
	defer fake.getAllTodosMutex.Unlock()
	fake.GetAllTodosStub = stub
}

func (fake *FakeDatabaseManagerInterface) GetAllTodosReturns(result1 []model.Todo, result2 error) {
	fake.getAllTodosMutex.Lock()
	defer fake.getAllTodosMutex.Unlock()
	fake.GetAllTodosStub = nil
	fake.getAllTodosReturns = struct {
		result1 []model.Todo
		result2 error
	}{result1, result2}
}

func (fake *FakeDatabaseManagerInterface) GetAllTodosReturnsOnCall(i int, result1 []model.Todo, result2 error) {
	fake.getAllTodosMutex.Lock()
	defer fake.getAllTodosMutex.Unlock()
	fake.GetAllTodosStub = nil
	if fake.getAllTodosReturnsOnCall == nil {
		fake.getAllTodosReturnsOnCall = make(map[int]struct {
			result1 []model.Todo
			result2 error
		})
	}
	fake.getAllTodosReturnsOnCall[i] = struct {
		result1 []model.Todo
		result2 error
	}{result1, result2}
}

func (fake *FakeDatabaseManagerInterface) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.closeDatabaseMutex.RLock()
	defer fake.closeDatabaseMutex.RUnlock()
	fake.establishDatabaseConnectionMutex.RLock()
	defer fake.establishDatabaseConnectionMutex.RUnlock()
	fake.getAllTodosMutex.RLock()
	defer fake.getAllTodosMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDatabaseManagerInterface) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ database.DatabaseManagerInterface = new(FakeDatabaseManagerInterface)
