// Code generated by counterfeiter. DO NOT EDIT.
package dbfakes

import (
	"sync"
	"todo-back/config"
	database "todo-back/db"
	"todo-back/model"
)

type FakeDatabaseManagerInterface struct {
	CloseDatabaseStub        func()
	closeDatabaseMutex       sync.RWMutex
	closeDatabaseArgsForCall []struct {
	}
	CreateTodoStub        func(string, bool) (*model.Todo, error)
	createTodoMutex       sync.RWMutex
	createTodoArgsForCall []struct {
		arg1 string
		arg2 bool
	}
	createTodoReturns struct {
		result1 *model.Todo
		result2 error
	}
	createTodoReturnsOnCall map[int]struct {
		result1 *model.Todo
		result2 error
	}
	DeleteTodoStub        func(int) error
	deleteTodoMutex       sync.RWMutex
	deleteTodoArgsForCall []struct {
		arg1 int
	}
	deleteTodoReturns struct {
		result1 error
	}
	deleteTodoReturnsOnCall map[int]struct {
		result1 error
	}
	EstablishDatabaseConnectionStub        func(config.Config) error
	establishDatabaseConnectionMutex       sync.RWMutex
	establishDatabaseConnectionArgsForCall []struct {
		arg1 config.Config
	}
	establishDatabaseConnectionReturns struct {
		result1 error
	}
	establishDatabaseConnectionReturnsOnCall map[int]struct {
		result1 error
	}
	GetAllTodosStub        func() ([]model.Todo, error)
	getAllTodosMutex       sync.RWMutex
	getAllTodosArgsForCall []struct {
	}
	getAllTodosReturns struct {
		result1 []model.Todo
		result2 error
	}
	getAllTodosReturnsOnCall map[int]struct {
		result1 []model.Todo
		result2 error
	}
	GetTodoStub        func(int) (*model.Todo, error)
	getTodoMutex       sync.RWMutex
	getTodoArgsForCall []struct {
		arg1 int
	}
	getTodoReturns struct {
		result1 *model.Todo
		result2 error
	}
	getTodoReturnsOnCall map[int]struct {
		result1 *model.Todo
		result2 error
	}
	UpdateTodoStub        func(int, string, bool) (*model.Todo, error)
	updateTodoMutex       sync.RWMutex
	updateTodoArgsForCall []struct {
		arg1 int
		arg2 string
		arg3 bool
	}
	updateTodoReturns struct {
		result1 *model.Todo
		result2 error
	}
	updateTodoReturnsOnCall map[int]struct {
		result1 *model.Todo
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDatabaseManagerInterface) CloseDatabase() {
	fake.closeDatabaseMutex.Lock()
	fake.closeDatabaseArgsForCall = append(fake.closeDatabaseArgsForCall, struct {
	}{})
	stub := fake.CloseDatabaseStub
	fake.recordInvocation("CloseDatabase", []interface{}{})
	fake.closeDatabaseMutex.Unlock()
	if stub != nil {
		fake.CloseDatabaseStub()
	}
}

func (fake *FakeDatabaseManagerInterface) CloseDatabaseCallCount() int {
	fake.closeDatabaseMutex.RLock()
	defer fake.closeDatabaseMutex.RUnlock()
	return len(fake.closeDatabaseArgsForCall)
}

func (fake *FakeDatabaseManagerInterface) CloseDatabaseCalls(stub func()) {
	fake.closeDatabaseMutex.Lock()
	defer fake.closeDatabaseMutex.Unlock()
	fake.CloseDatabaseStub = stub
}

func (fake *FakeDatabaseManagerInterface) CreateTodo(arg1 string, arg2 bool) (*model.Todo, error) {
	fake.createTodoMutex.Lock()
	ret, specificReturn := fake.createTodoReturnsOnCall[len(fake.createTodoArgsForCall)]
	fake.createTodoArgsForCall = append(fake.createTodoArgsForCall, struct {
		arg1 string
		arg2 bool
	}{arg1, arg2})
	stub := fake.CreateTodoStub
	fakeReturns := fake.createTodoReturns
	fake.recordInvocation("CreateTodo", []interface{}{arg1, arg2})
	fake.createTodoMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDatabaseManagerInterface) CreateTodoCallCount() int {
	fake.createTodoMutex.RLock()
	defer fake.createTodoMutex.RUnlock()
	return len(fake.createTodoArgsForCall)
}

func (fake *FakeDatabaseManagerInterface) CreateTodoCalls(stub func(string, bool) (*model.Todo, error)) {
	fake.createTodoMutex.Lock()
	defer fake.createTodoMutex.Unlock()
	fake.CreateTodoStub = stub
}

func (fake *FakeDatabaseManagerInterface) CreateTodoArgsForCall(i int) (string, bool) {
	fake.createTodoMutex.RLock()
	defer fake.createTodoMutex.RUnlock()
	argsForCall := fake.createTodoArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeDatabaseManagerInterface) CreateTodoReturns(result1 *model.Todo, result2 error) {
	fake.createTodoMutex.Lock()
	defer fake.createTodoMutex.Unlock()
	fake.CreateTodoStub = nil
	fake.createTodoReturns = struct {
		result1 *model.Todo
		result2 error
	}{result1, result2}
}

func (fake *FakeDatabaseManagerInterface) CreateTodoReturnsOnCall(i int, result1 *model.Todo, result2 error) {
	fake.createTodoMutex.Lock()
	defer fake.createTodoMutex.Unlock()
	fake.CreateTodoStub = nil
	if fake.createTodoReturnsOnCall == nil {
		fake.createTodoReturnsOnCall = make(map[int]struct {
			result1 *model.Todo
			result2 error
		})
	}
	fake.createTodoReturnsOnCall[i] = struct {
		result1 *model.Todo
		result2 error
	}{result1, result2}
}

func (fake *FakeDatabaseManagerInterface) DeleteTodo(arg1 int) error {
	fake.deleteTodoMutex.Lock()
	ret, specificReturn := fake.deleteTodoReturnsOnCall[len(fake.deleteTodoArgsForCall)]
	fake.deleteTodoArgsForCall = append(fake.deleteTodoArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.DeleteTodoStub
	fakeReturns := fake.deleteTodoReturns
	fake.recordInvocation("DeleteTodo", []interface{}{arg1})
	fake.deleteTodoMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDatabaseManagerInterface) DeleteTodoCallCount() int {
	fake.deleteTodoMutex.RLock()
	defer fake.deleteTodoMutex.RUnlock()
	return len(fake.deleteTodoArgsForCall)
}

func (fake *FakeDatabaseManagerInterface) DeleteTodoCalls(stub func(int) error) {
	fake.deleteTodoMutex.Lock()
	defer fake.deleteTodoMutex.Unlock()
	fake.DeleteTodoStub = stub
}

func (fake *FakeDatabaseManagerInterface) DeleteTodoArgsForCall(i int) int {
	fake.deleteTodoMutex.RLock()
	defer fake.deleteTodoMutex.RUnlock()
	argsForCall := fake.deleteTodoArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDatabaseManagerInterface) DeleteTodoReturns(result1 error) {
	fake.deleteTodoMutex.Lock()
	defer fake.deleteTodoMutex.Unlock()
	fake.DeleteTodoStub = nil
	fake.deleteTodoReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDatabaseManagerInterface) DeleteTodoReturnsOnCall(i int, result1 error) {
	fake.deleteTodoMutex.Lock()
	defer fake.deleteTodoMutex.Unlock()
	fake.DeleteTodoStub = nil
	if fake.deleteTodoReturnsOnCall == nil {
		fake.deleteTodoReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteTodoReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDatabaseManagerInterface) EstablishDatabaseConnection(arg1 config.Config) error {
	fake.establishDatabaseConnectionMutex.Lock()
	ret, specificReturn := fake.establishDatabaseConnectionReturnsOnCall[len(fake.establishDatabaseConnectionArgsForCall)]
	fake.establishDatabaseConnectionArgsForCall = append(fake.establishDatabaseConnectionArgsForCall, struct {
		arg1 config.Config
	}{arg1})
	stub := fake.EstablishDatabaseConnectionStub
	fakeReturns := fake.establishDatabaseConnectionReturns
	fake.recordInvocation("EstablishDatabaseConnection", []interface{}{arg1})
	fake.establishDatabaseConnectionMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDatabaseManagerInterface) EstablishDatabaseConnectionCallCount() int {
	fake.establishDatabaseConnectionMutex.RLock()
	defer fake.establishDatabaseConnectionMutex.RUnlock()
	return len(fake.establishDatabaseConnectionArgsForCall)
}

func (fake *FakeDatabaseManagerInterface) EstablishDatabaseConnectionCalls(stub func(config.Config) error) {
	fake.establishDatabaseConnectionMutex.Lock()
	defer fake.establishDatabaseConnectionMutex.Unlock()
	fake.EstablishDatabaseConnectionStub = stub
}

func (fake *FakeDatabaseManagerInterface) EstablishDatabaseConnectionArgsForCall(i int) config.Config {
	fake.establishDatabaseConnectionMutex.RLock()
	defer fake.establishDatabaseConnectionMutex.RUnlock()
	argsForCall := fake.establishDatabaseConnectionArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDatabaseManagerInterface) EstablishDatabaseConnectionReturns(result1 error) {
	fake.establishDatabaseConnectionMutex.Lock()
	defer fake.establishDatabaseConnectionMutex.Unlock()
	fake.EstablishDatabaseConnectionStub = nil
	fake.establishDatabaseConnectionReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDatabaseManagerInterface) EstablishDatabaseConnectionReturnsOnCall(i int, result1 error) {
	fake.establishDatabaseConnectionMutex.Lock()
	defer fake.establishDatabaseConnectionMutex.Unlock()
	fake.EstablishDatabaseConnectionStub = nil
	if fake.establishDatabaseConnectionReturnsOnCall == nil {
		fake.establishDatabaseConnectionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.establishDatabaseConnectionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDatabaseManagerInterface) GetAllTodos() ([]model.Todo, error) {
	fake.getAllTodosMutex.Lock()
	ret, specificReturn := fake.getAllTodosReturnsOnCall[len(fake.getAllTodosArgsForCall)]
	fake.getAllTodosArgsForCall = append(fake.getAllTodosArgsForCall, struct {
	}{})
	stub := fake.GetAllTodosStub
	fakeReturns := fake.getAllTodosReturns
	fake.recordInvocation("GetAllTodos", []interface{}{})
	fake.getAllTodosMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDatabaseManagerInterface) GetAllTodosCallCount() int {
	fake.getAllTodosMutex.RLock()
	defer fake.getAllTodosMutex.RUnlock()
	return len(fake.getAllTodosArgsForCall)
}

func (fake *FakeDatabaseManagerInterface) GetAllTodosCalls(stub func() ([]model.Todo, error)) {
	fake.getAllTodosMutex.Lock()
	defer fake.getAllTodosMutex.Unlock()
	fake.GetAllTodosStub = stub
}

func (fake *FakeDatabaseManagerInterface) GetAllTodosReturns(result1 []model.Todo, result2 error) {
	fake.getAllTodosMutex.Lock()
	defer fake.getAllTodosMutex.Unlock()
	fake.GetAllTodosStub = nil
	fake.getAllTodosReturns = struct {
		result1 []model.Todo
		result2 error
	}{result1, result2}
}

func (fake *FakeDatabaseManagerInterface) GetAllTodosReturnsOnCall(i int, result1 []model.Todo, result2 error) {
	fake.getAllTodosMutex.Lock()
	defer fake.getAllTodosMutex.Unlock()
	fake.GetAllTodosStub = nil
	if fake.getAllTodosReturnsOnCall == nil {
		fake.getAllTodosReturnsOnCall = make(map[int]struct {
			result1 []model.Todo
			result2 error
		})
	}
	fake.getAllTodosReturnsOnCall[i] = struct {
		result1 []model.Todo
		result2 error
	}{result1, result2}
}

func (fake *FakeDatabaseManagerInterface) GetTodo(arg1 int) (*model.Todo, error) {
	fake.getTodoMutex.Lock()
	ret, specificReturn := fake.getTodoReturnsOnCall[len(fake.getTodoArgsForCall)]
	fake.getTodoArgsForCall = append(fake.getTodoArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.GetTodoStub
	fakeReturns := fake.getTodoReturns
	fake.recordInvocation("GetTodo", []interface{}{arg1})
	fake.getTodoMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDatabaseManagerInterface) GetTodoCallCount() int {
	fake.getTodoMutex.RLock()
	defer fake.getTodoMutex.RUnlock()
	return len(fake.getTodoArgsForCall)
}

func (fake *FakeDatabaseManagerInterface) GetTodoCalls(stub func(int) (*model.Todo, error)) {
	fake.getTodoMutex.Lock()
	defer fake.getTodoMutex.Unlock()
	fake.GetTodoStub = stub
}

func (fake *FakeDatabaseManagerInterface) GetTodoArgsForCall(i int) int {
	fake.getTodoMutex.RLock()
	defer fake.getTodoMutex.RUnlock()
	argsForCall := fake.getTodoArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDatabaseManagerInterface) GetTodoReturns(result1 *model.Todo, result2 error) {
	fake.getTodoMutex.Lock()
	defer fake.getTodoMutex.Unlock()
	fake.GetTodoStub = nil
	fake.getTodoReturns = struct {
		result1 *model.Todo
		result2 error
	}{result1, result2}
}

func (fake *FakeDatabaseManagerInterface) GetTodoReturnsOnCall(i int, result1 *model.Todo, result2 error) {
	fake.getTodoMutex.Lock()
	defer fake.getTodoMutex.Unlock()
	fake.GetTodoStub = nil
	if fake.getTodoReturnsOnCall == nil {
		fake.getTodoReturnsOnCall = make(map[int]struct {
			result1 *model.Todo
			result2 error
		})
	}
	fake.getTodoReturnsOnCall[i] = struct {
		result1 *model.Todo
		result2 error
	}{result1, result2}
}

func (fake *FakeDatabaseManagerInterface) UpdateTodo(arg1 int, arg2 string, arg3 bool) (*model.Todo, error) {
	fake.updateTodoMutex.Lock()
	ret, specificReturn := fake.updateTodoReturnsOnCall[len(fake.updateTodoArgsForCall)]
	fake.updateTodoArgsForCall = append(fake.updateTodoArgsForCall, struct {
		arg1 int
		arg2 string
		arg3 bool
	}{arg1, arg2, arg3})
	stub := fake.UpdateTodoStub
	fakeReturns := fake.updateTodoReturns
	fake.recordInvocation("UpdateTodo", []interface{}{arg1, arg2, arg3})
	fake.updateTodoMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDatabaseManagerInterface) UpdateTodoCallCount() int {
	fake.updateTodoMutex.RLock()
	defer fake.updateTodoMutex.RUnlock()
	return len(fake.updateTodoArgsForCall)
}

func (fake *FakeDatabaseManagerInterface) UpdateTodoCalls(stub func(int, string, bool) (*model.Todo, error)) {
	fake.updateTodoMutex.Lock()
	defer fake.updateTodoMutex.Unlock()
	fake.UpdateTodoStub = stub
}

func (fake *FakeDatabaseManagerInterface) UpdateTodoArgsForCall(i int) (int, string, bool) {
	fake.updateTodoMutex.RLock()
	defer fake.updateTodoMutex.RUnlock()
	argsForCall := fake.updateTodoArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeDatabaseManagerInterface) UpdateTodoReturns(result1 *model.Todo, result2 error) {
	fake.updateTodoMutex.Lock()
	defer fake.updateTodoMutex.Unlock()
	fake.UpdateTodoStub = nil
	fake.updateTodoReturns = struct {
		result1 *model.Todo
		result2 error
	}{result1, result2}
}

func (fake *FakeDatabaseManagerInterface) UpdateTodoReturnsOnCall(i int, result1 *model.Todo, result2 error) {
	fake.updateTodoMutex.Lock()
	defer fake.updateTodoMutex.Unlock()
	fake.UpdateTodoStub = nil
	if fake.updateTodoReturnsOnCall == nil {
		fake.updateTodoReturnsOnCall = make(map[int]struct {
			result1 *model.Todo
			result2 error
		})
	}
	fake.updateTodoReturnsOnCall[i] = struct {
		result1 *model.Todo
		result2 error
	}{result1, result2}
}

func (fake *FakeDatabaseManagerInterface) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.closeDatabaseMutex.RLock()
	defer fake.closeDatabaseMutex.RUnlock()
	fake.createTodoMutex.RLock()
	defer fake.createTodoMutex.RUnlock()
	fake.deleteTodoMutex.RLock()
	defer fake.deleteTodoMutex.RUnlock()
	fake.establishDatabaseConnectionMutex.RLock()
	defer fake.establishDatabaseConnectionMutex.RUnlock()
	fake.getAllTodosMutex.RLock()
	defer fake.getAllTodosMutex.RUnlock()
	fake.getTodoMutex.RLock()
	defer fake.getTodoMutex.RUnlock()
	fake.updateTodoMutex.RLock()
	defer fake.updateTodoMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDatabaseManagerInterface) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ database.DatabaseManagerInterface = new(FakeDatabaseManagerInterface)
